### ISSUE TITLE
Add LLM Memory Management Feature

### ISSUE THREAD

**Issue by Goldziher** [Goldziher/ai-rulez#5]
## Overview
Extend ai-rulez to support LLM memory management, allowing users to easily record, categorize, and output contextual memories for AI assistants.

## Problem Statement
Developers often need to maintain context and memories across LLM sessions, but there's no standardized way to:
- Record important decisions, solutions, and learnings
- Categorize and prioritize memories by relevance
- Generate different memory formats for different AI assistants
- Share knowledge across team members and projects

## Proposed Solution
Add memory management capabilities to ai-rulez configuration format:

### YAML Schema Extension
```yaml
metadata:
  name: "Project Memories"

memories:
  - title: "API Design Decision"
    category: "architecture" 
    priority: 10
    timestamp: "2024-01-15"
    context: "user-service"
    content: |
      Decided to use REST over GraphQL because...
      Key considerations were...
    tags: ["api", "rest", "decision"]

categories:
  - name: "architecture"
    description: "System design decisions"
  - name: "debugging"
    description: "Bug solutions and workarounds"
  - name: "performance"
    description: "Optimization techniques"

outputs:
  - file: "MEMORIES.md"
    template: "memory-log"
  - file: ".claude-memory"
    template: "claude-context"
```

### Memory Management
```bash
# Add new memory
ai-rulez add-memory "Bug Fix: OAuth Token Refresh" \
  --category debugging \
  --priority 8 \
  --context auth-service \
  --tags oauth,bug,security

# List memories
ai-rulez list-memories [--category architecture] [--context user-service]

# Search memories
ai-rulez search-memories "performance optimization"

# Edit memory
ai-rulez edit-memory "API Design Decision"

# Remove memory
ai-rulez remove-memory "Old Solution" [--confirm]
```

### Category Management
```bash
# Add category
ai-rulez add-category "security" "Security-related decisions and patterns"

# List categories
ai-rulez list-categories
```

### Core Functionality
- [ ] Extend YAML schema to support memories and categories
- [ ] Memory CRUD operations via CLI
- [ ] Category management
- [ ] Tag-based organization
- [ ] Context/project association
- [ ] Timestamp tracking
- [ ] Priority-based sorting

### Output Templates
- [ ] Memory log template (Markdown)
- [ ] Claude context template
- [ ] Cursor memory format
- [ ] JSON export for programmatic access
- [ ] Search index generation

### Advanced Features
- [ ] Memory linking (reference other memories)
- [ ] Expiration dates for time-sensitive memories
- [ ] Memory validation (required fields, formats)
- [ ] Import/export between projects
- [ ] Memory statistics and analytics
- [ ] Interactive memory browser

### Development Team
- Architecture decision records (ADRs)
- Bug solutions and workarounds
- Performance optimization techniques
- Code review insights
- Deployment procedures

### Personal Learning
- Language-specific patterns
- Framework best practices
- Tool configurations
- Debugging techniques
- Career learnings

### Project Context
- Domain knowledge
- Business rule explanations  
- Integration patterns
- Testing strategies
- Monitoring insights

### Schema Changes
- Extend JSON schema for memories and categories
- Add validation rules for memory structure
- Support for optional fields and defaults

### CLI Architecture
- New memory command group under main CLI
- Reuse existing config discovery and validation
- Extend template system for memory outputs
- Add search/filter capabilities

### Template System
- Built-in templates for common memory formats
- Custom template support
- Variable substitution for timestamps, context
- Conditional rendering based on categories

### Data Management
- Atomic updates to preserve existing config
- Backup creation before modifications
- Conflict resolution for concurrent edits
- Migration support for schema updates

## Success Metrics
- Adoption rate among existing ai-rulez users
- Memory entries created per user
- Template usage patterns
- Community contributions of memory templates

## Future Enhancements
- AI-powered memory suggestions
- Integration with git commits for automatic memory creation
- Memory sharing marketplace
- LLM fine-tuning data export
- Memory quality scoring
- Collaborative memory editing

## Dependencies
- Extend existing config package for new schema
- Add search/indexing capabilities
- Template engine enhancements
- CLI command structure expansion

---

This feature would make ai-rulez a comprehensive knowledge management tool for developers working with AI assistants, providing structured memory persistence across sessions and projects.
